#!/usr/bin/env python3
"""Remove canonical classes from every label file and re-index the survivors.

YOLO label files store a bare integer per box. Removing a class from the schema
therefore CANNOT be done in config alone: every id above the removed one shifts
down, and any file still carrying an old id is silently reinterpreted as whatever
class now owns that number. Dropping Pedestrian Lane (14) alone makes Bicycle
15 -> 14; dropping Stairs (5), Elevator (13) and Pedestrian Lane (14) together
re-indexes eight classes.

Run this BEFORE editing config/classes.yaml. It derives the mapping from the
CURRENT CANONICAL_NAMES, so it refuses to run once the config has already changed
-- at that point the old ids are unrecoverable.

Only dataset/processed/<source>/{labels,labels_reviewed}/ are migrated: those are
the sources of truth. dataset/merged/ and dataset/final/ are regenerated by the
cascade (cap_per_class -> merge -> dedup -> split -> generate_yaml) and are not
worth migrating in place; pass --include-derived if you want them done anyway.

    python3 scripts/preprocess/drop_classes.py --drop "Pedestrian Lane" --dry-run
    python3 scripts/preprocess/drop_classes.py --drop Stairs Elevator "Pedestrian Lane"
"""
from __future__ import annotations

import argparse
import datetime
import json
import shutil
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
from utils.config_loader import CANONICAL_NAMES  # noqa: E402
from utils.file_utils import processed_dir, reports_dir  # noqa: E402

REPO = Path(__file__).resolve().parents[2]


def build_map(drop: list[str]) -> tuple[dict[int, int], set[int], list[str]]:
    missing = [d for d in drop if d not in CANONICAL_NAMES]
    if missing:
        raise SystemExit(
            f"Not in CANONICAL_NAMES: {missing}\n"
            f"Current schema ({len(CANONICAL_NAMES)}): {CANONICAL_NAMES}\n"
            "If these were already removed from config, the migration has run or the "
            "config was edited first -- old ids cannot be recovered from the files alone."
        )
    survivors = [n for n in CANONICAL_NAMES if n not in drop]
    remap = {
        CANONICAL_NAMES.index(n): survivors.index(n)
        for n in survivors
    }
    dropped_ids = {CANONICAL_NAMES.index(n) for n in drop}
    return remap, dropped_ids, survivors


def target_dirs(include_derived: bool) -> list[Path]:
    dirs = []
    for path in sorted(processed_dir().iterdir()):
        if not path.is_dir():
            continue
        for sub in ("labels", "labels_reviewed"):
            d = path / sub
            if d.is_dir() and any(d.glob("*.txt")):
                dirs.append(d)
    if include_derived:
        for d in [REPO / "dataset/merged/labels"] + [
            REPO / f"dataset/final/{s}/labels" for s in ("train", "val", "test")
        ]:
            if d.is_dir() and any(d.glob("*.txt")):
                dirs.append(d)
    return dirs


def migrate_dir(d: Path, remap: dict[int, int], dropped: set[int], dry_run: bool) -> dict:
    touched = emptied = removed_boxes = 0
    files = sorted(d.glob("*.txt"))
    pending: list[tuple[Path, str]] = []
    for f in files:
        lines = [l for l in f.read_text(encoding="utf-8").splitlines() if l.strip()]
        out = []
        changed = False
        for line in lines:
            parts = line.split()
            cid = int(parts[0])
            if cid in dropped:
                removed_boxes += 1
                changed = True
                continue
            new_id = remap[cid]
            if new_id != cid:
                changed = True
            out.append(" ".join([str(new_id)] + parts[1:]))
        if not changed:
            continue
        touched += 1
        if not out:
            emptied += 1
        pending.append((f, "\n".join(out) + ("\n" if out else "")))

    backup = None
    if pending and not dry_run:
        stamp = datetime.datetime.now().strftime("%Y%m%d_%H%M%S")
        backup = d.parent / f"{d.name}_pre_classdrop_bak_{stamp}"
        shutil.copytree(d, backup)
        for path, text in pending:
            path.write_text(text, encoding="utf-8")
    return {
        "dir": str(d.relative_to(REPO)),
        "files": len(files),
        "touched": touched,
        "emptied": emptied,
        "removed_boxes": removed_boxes,
        "backup": str(backup.relative_to(REPO)) if backup else None,
    }


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--drop", nargs="+", required=True, help="canonical class name(s) to remove")
    ap.add_argument("--dry-run", action="store_true")
    ap.add_argument("--include-derived", action="store_true", help="also migrate dataset/merged and dataset/final")
    ap.add_argument("--force", action="store_true", help="run even if a prior migration stamp exists")
    args = ap.parse_args()

    remap, dropped, survivors = build_map(args.drop)

    prior = sorted(reports_dir().glob("class_migration_*.json"))
    if prior and not args.force and not args.dry_run:
        raise SystemExit(
            f"A previous migration stamp exists: {prior[-1].name}\n"
            "Running twice would re-index already-migrated files and corrupt them. "
            "Pass --force only if you are certain this is a different, un-run migration."
        )

    print(f"schema {len(CANONICAL_NAMES)} -> {len(survivors)}   dropping {args.drop}")
    for i, n in enumerate(CANONICAL_NAMES):
        print(f"  {i:>2} {n:<18}-> {remap[i] if i in remap else 'REMOVED'}")

    dirs = target_dirs(args.include_derived)
    print(f"\n{len(dirs)} label directories\n")
    tot = {"files": 0, "touched": 0, "emptied": 0, "removed_boxes": 0}
    results = []
    for d in dirs:
        r = migrate_dir(d, remap, dropped, args.dry_run)
        results.append(r)
        for k in tot:
            tot[k] += r[k]
        if r["touched"]:
            print(f"  {r['dir']:<62} touched {r['touched']:>6}  emptied {r['emptied']:>5}  boxes -{r['removed_boxes']}")
    print(
        f"\n{'WOULD CHANGE' if args.dry_run else 'CHANGED'}: {tot['touched']} of {tot['files']} files, "
        f"{tot['removed_boxes']} boxes removed, {tot['emptied']} files left with zero boxes"
    )
    print(
        "Files left with zero boxes are not deleted -- cap_per_class.py indexes by the "
        "class ids present, so an empty file is a candidate for nothing and never reaches merged/."
    )
    if not args.dry_run:
        stamp_path = reports_dir() / f"class_migration_{datetime.datetime.now():%Y%m%d_%H%M%S}.json"
        stamp_path.write_text(json.dumps({
            "dropped": args.drop, "old_schema": CANONICAL_NAMES, "new_schema": survivors,
            "remap": {str(k): v for k, v in remap.items()}, "totals": tot,
            "dirs": results,
        }, indent=2), encoding="utf-8")
        print(f"\nstamp written -> {stamp_path.relative_to(REPO)}")
        print("NEXT: update config/classes.yaml + CANONICAL_NAMES, then re-run the cascade.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
