#!/usr/bin/env python3
"""Snapshot everything needed to reconstruct the current class schema and review work.

Taken before a destructive schema change (drop_classes.py) so the decision stays
reversible. dataset/processed/ is gitignored, so for labels_reviewed/ -- hand-drawn
and hand-verified boxes that no script can regenerate -- this snapshot is the only
copy that exists outside the live tree.

Captures:
  config/classes.yaml, config/datasets.yaml   the schema and source mapping
  dataset/reports/*.json                      exclusions, cap and dedup reports
  processed/<source>/labels/                  converted labels (regenerable from raw)
  processed/<source>/labels_reviewed/         hand review work (NOT regenerable)
  fiftyone/<name>/                            review datasets: tags, predictions,
                                              accept/dup_gt state, exclusions
  MANIFEST.json                               schema, per-class counts, restore notes

Deliberately NOT captured: dataset/raw/ (never modified by any migration, and large),
dataset/merged/ and dataset/final/ (regenerated by the cascade), and image files
(FiftyOne datasets are exported with export_media=False and reference paths in place).

    python3 scripts/preprocess/snapshot_state.py --label pre_class_drop
"""
from __future__ import annotations

import argparse
import datetime
import json
import shutil
import sys
from collections import Counter
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
from utils.config_loader import CANONICAL_NAMES  # noqa: E402
from utils.file_utils import processed_dir, reports_dir  # noqa: E402

REPO = Path(__file__).resolve().parents[2]


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--label", default="snapshot", help="name stem for the snapshot dir")
    ap.add_argument("--no-fiftyone", action="store_true", help="skip exporting FiftyOne review datasets")
    args = ap.parse_args()

    stamp = datetime.datetime.now().strftime("%Y%m%d_%H%M%S")
    out = REPO / "dataset" / "backups" / f"{args.label}_{stamp}"
    out.mkdir(parents=True, exist_ok=False)

    manifest: dict = {
        "created": stamp,
        "canonical_names": CANONICAL_NAMES,
        "class_count": len(CANONICAL_NAMES),
        "restore_notes": [
            "labels_reviewed/ is hand work and cannot be regenerated -- restore it from here.",
            "labels/ can also be rebuilt by re-running yolo_to_intermediate.py against dataset/raw/.",
            "FiftyOne datasets were exported WITHOUT media; re-import with "
            "fo.Dataset.from_dir(..., dataset_type=fo.types.FiftyOneDataset) while the "
            "image files are still at their recorded paths.",
            "Class ids in these files follow canonical_names above. After a schema change "
            "they must be re-mapped before use.",
        ],
        "sources": {},
        "fiftyone": {},
    }

    # config + reports
    (out / "config").mkdir()
    for name in ("classes.yaml", "datasets.yaml"):
        shutil.copy2(REPO / "config" / name, out / "config" / name)
    shutil.copytree(reports_dir(), out / "reports")

    # label dirs
    id2 = {i: n for i, n in enumerate(CANONICAL_NAMES)}
    for src in sorted(processed_dir().iterdir()):
        if not src.is_dir():
            continue
        entry = {}
        for sub in ("labels", "labels_reviewed"):
            d = src / sub
            if not d.is_dir() or not any(d.glob("*.txt")):
                continue
            dest = out / "processed" / src.name / sub
            dest.parent.mkdir(parents=True, exist_ok=True)
            shutil.copytree(d, dest)
            counts = Counter()
            for f in d.glob("*.txt"):
                for line in f.read_text(encoding="utf-8").splitlines():
                    parts = line.split()
                    if len(parts) == 5:
                        counts[id2[int(parts[0])]] += 1
            entry[sub] = {"files": len(list(d.glob("*.txt"))), "boxes": dict(counts)}
        if entry:
            manifest["sources"][src.name] = entry

    # FiftyOne review datasets
    if not args.no_fiftyone:
        import fiftyone as fo

        for name in sorted(fo.list_datasets()):
            if not name.startswith(("review_", "verify_")):
                continue
            ds = fo.load_dataset(name)
            ds.reload()
            dest = out / "fiftyone" / name
            ds.export(
                export_dir=str(dest),
                dataset_type=fo.types.FiftyOneDataset,
                export_media=False,
            )
            manifest["fiftyone"][name] = {
                "samples": len(ds),
                "sample_tags": dict(ds.count_sample_tags()),
                "label_tags": dict(ds.count_label_tags()),
            }

    (out / "MANIFEST.json").write_text(json.dumps(manifest, indent=2), encoding="utf-8")

    size = sum(f.stat().st_size for f in out.rglob("*") if f.is_file())
    print(f"snapshot -> {out.relative_to(REPO)}")
    print(f"  {len(manifest['sources'])} source(s), {len(manifest['fiftyone'])} FiftyOne dataset(s)")
    print(f"  {sum(1 for _ in out.rglob('*') if _.is_file())} files, {size / 1e6:.1f} MB")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
