#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

# Values live here, not in .env — pod IPs are per-session scratch and .env.* is
# already gitignored. Set before any write_env call.
ENV_FILE=".env.runpod"

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
BUNDLE_TAR="${REPO_ROOT}/dataset/bundle.tar"
EXPECT_SHA="f71d355e7d394cbcc1edf5405a04ee2c2f549605b1ef8491c7b6c81cd5d249cc"
REPO_URL="https://github.com/KRMeeag/second-vision-ai.git"

# Which ablation arm this run materialises and trains. 4500 is the baseline and
# the only committed condition (DEC-121); 9000 and 1500 are optional follow-ups.
# A second arm needs no new upload -- the bundle already holds the cap-9000
# superset -- so re-running from stage 9 is all it takes:
#     CAP=9000 START_AT=9 scripts/train/runpod_wizard.sh
CAP="${CAP:-4500}"
case "$CAP" in 1500|4500|9000) ;; *) echo "CAP must be 1500, 4500 or 9000 (got $CAP)"; exit 2 ;; esac
# Expected split sizes per condition, from dataset/bundle/bundle_meta.json.
# val/test are frozen and identical across conditions (DEC-119); only train varies.
case "$CAP" in
  1500) EXP_TRAIN=14202 ;;
  4500) EXP_TRAIN=30123 ;;
  9000) EXP_TRAIN=41467 ;;
esac
COND="final_cap${CAP}"

TOTAL_STAGES=14

# ── authored helpers ──────────────────────────────────────────────────────

# _at — support resuming: START_AT=7 ./runpod_wizard.sh replays nothing before
# stage 7. The upload stage runs for ~2 h; being forced to click through nine
# stages to get back to it would make Ctrl-C expensive.
_at() { [[ "$_STAGE_INDEX" -ge "${START_AT:-1}" ]]; }

# gate "desc" cmd... — run a check and REFUSE to advance until it passes.
# This is the entire reason this wizard exists rather than a document. A runbook
# can tell you to verify before terminating a pod; only a gate can stop you.
gate() {
  local desc="$1"; shift
  while true; do
    if "$@"; then
      printf '  %s✓ %s%s\n' "$GREEN" "$desc" "$RESET"
      return 0
    fi
    printf '\n'; warn "$desc — FAILED"
    say "Fix the problem above, then press Enter to re-check."
    note "Ctrl-C aborts. Resume later with:  START_AT=${_STAGE_INDEX} $0"
    pause "Press Enter to re-check"
  done
}

# podssh HOST PORT cmd... — run a command on a pod over the direct TCP SSH.
podssh() {
  local host="$1" port="$2"; shift 2
  ssh -p "$port" -i "$SSH_KEY" \
      -o StrictHostKeyChecking=accept-new -o ConnectTimeout=20 \
      -o ServerAliveInterval=15 -o ServerAliveCountMax=4 \
      "root@${host}" "$@"
}

VERIFIED_OK=0   # set to 1 only when verify_bundle.py passes; gates the terminate

# ──────────────────────────────────────────────────────────────────────────

banner "Second Vision — RunPod training, Phases 1-4 (cap${CAP})"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "Preflight — archive, checksum, repo, rsync"
if _at; then
say "Checking everything that must be true before you spend money or bandwidth."
gate "dataset/bundle.tar exists" test -f "$BUNDLE_TAR"
say "Verifying the archive checksum (~30 s for 5.1 GB)..."
gate "archive checksum matches DEC-119" bash -c \
  "[ \"\$(shasum -a 256 '$BUNDLE_TAR' | awk '{print \$1}')\" = '$EXPECT_SHA' ]"

step "The pod clones the repo from GitHub — anything uncommitted will not exist there."
if ! git -C "$REPO_ROOT" diff --quiet || ! git -C "$REPO_ROOT" diff --cached --quiet \
   || [ -n "$(git -C "$REPO_ROOT" ls-files --others --exclude-standard)" ]; then
  warn "You have uncommitted or untracked files:"
  git -C "$REPO_ROOT" status --short | sed 's/^/    /'
  say "scripts/train/verify_bundle.py in particular MUST be pushed — it is how"
  say "you prove the transfer landed intact."
  pause "Commit and push in another terminal, then press Enter"
fi
say "Fetching origin so the push check compares against the real remote..."
git -C "$REPO_ROOT" fetch origin --quiet || warn "fetch failed — push check may be stale"
gate "local branch is pushed to origin" bash -c \
  "[ -z \"\$(git -C '$REPO_ROOT' log --oneline origin/main..HEAD 2>/dev/null)\" ]"

if /usr/bin/rsync --version 2>&1 | head -1 | grep -qi openrsync \
   && ! [ -x /opt/homebrew/bin/rsync ]; then
  note "macOS ships openrsync, which lacks --append-verify. The upload works either"
  note "way (upload_bundle.sh adapts), but GNU rsync makes retries cheaper."
  if confirm "Install GNU rsync now (brew install rsync)?"; then
    brew install rsync || warn "brew install failed — continuing with openrsync"
  fi
fi

ask SSH_KEY "Path to your SSH private key [~/.ssh/id_ed25519]:"
[[ -z "$SSH_KEY" ]] && SSH_KEY="$HOME/.ssh/id_ed25519"
SSH_KEY="${SSH_KEY/#\~/$HOME}"
gate "SSH private key exists" test -f "$SSH_KEY"
write_env SSH_KEY "$SSH_KEY"
fi

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "RunPod — add your SSH public key (BEFORE any pod exists)"
if _at; then
warn "RunPod injects public keys at pod START. A key added afterwards needs a restart."
say "Your public key:"
if [[ -f "${SSH_KEY}.pub" ]]; then
  printf '\n'; sed 's/^/    /' "${SSH_KEY}.pub"; printf '\n'
else
  warn "No ${SSH_KEY}.pub found — deriving it from the private key:"
  printf '\n'; ssh-keygen -y -f "$SSH_KEY" | sed 's/^/    /'; printf '\n'
fi
open_url "https://console.runpod.io/user/settings"
step "Settings → SSH Public Keys → paste the key above → Update."
pause "Press Enter once the key is saved"
fi

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "RunPod — datacenter and the 30 GB network volume"
if _at; then
warn "Pick the DATACENTER first. Network volumes are datacenter-scoped and a pod"
warn "can only mount a volume in its own datacenter."
say "If you create the volume somewhere with no RTX 4090 stock, the fix is deleting"
say "it and re-uploading — 2.2 hours. Check 4090 availability BEFORE creating it."
open_url "https://console.runpod.io/deploy"
step "Browse GPU availability and note a datacenter that has RTX 4090 in stock."
ask RUNPOD_DATACENTER "Which datacenter did you choose? (e.g. EU-RO-1):"
write_env RUNPOD_DATACENTER "$RUNPOD_DATACENTER"
open_url "https://console.runpod.io/user/storage"
step "Storage → New Network Volume → datacenter ${RUNPOD_DATACENTER} → size 30 GB."
note "~\$2.10/month. Steady state is ~11.4 GB; the headroom covers all three"
note "ablation arms plus HEF exports. Python packages live in the container image,"
note "not the volume, so they do not count."
pause "Press Enter once the volume exists"
fi

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "RunPod — deploy the CPU pod for the upload"
if _at; then
say "The upload needs no GPU. Two hours of idle 4090 costs ~\$0.90; a CPU pod ~\$0.30."
open_url "https://console.runpod.io/deploy"
step "Deploy a CPU pod in ${RUNPOD_DATACENTER}, ATTACHING the network volume."
step "General Purpose, 2 vCPU / 8 GB is ample — this workload is I/O bound and the"
step "heaviest step peaks at 60 MB of RAM."
step "Make sure the template exposes TCP port 22."
note "If no CPU pod is offered in this datacenter, deploy the 4090 instead and use"
note "it for the upload — under a dollar more, and not worth changing datacenter for."
printf '\n'
warn "Use 'SSH over exposed TCP' from the Connect panel — NOT ssh.runpod.io."
warn "The proxy form is a restricted shell with no rsync on the far side."
ask CPU_POD_HOST "Pod IP address:"
ask CPU_POD_PORT "Pod SSH port:"
write_env CPU_POD_HOST "$CPU_POD_HOST"
write_env CPU_POD_PORT "$CPU_POD_PORT"
fi

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "Connectivity gate — prove SSH and the volume before a 2 h transfer"
if _at; then
say "Failing here costs seconds. Failing after the transfer starts costs hours."
gate "SSH to the CPU pod works" podssh "$CPU_POD_HOST" "$CPU_POD_PORT" true
gate "/workspace is the mounted network volume (not container disk)" \
  podssh "$CPU_POD_HOST" "$CPU_POD_PORT" \
  "mountpoint -q /workspace || df -h /workspace | tail -1 | grep -qv overlay"
podssh "$CPU_POD_HOST" "$CPU_POD_PORT" "df -h /workspace | sed 's/^/    /'"
note "If that shows an 'overlay' filesystem, the volume is NOT attached — stop and"
note "re-deploy the pod with the network volume mounted, or the upload dies with it."
pause "Press Enter to continue"
fi

# ── 6 ─────────────────────────────────────────────────────────────────────
stage "Upload — ~2.2 h, resumable, unattended"
if _at; then
say "upload_bundle.sh retries with backoff through dropped connections and compares"
say "the remote sha256 before reporting success. You can walk away."
note "Ctrl-C is safe: the partial file stays on the volume and re-running resumes."
note "Resume this wizard at this point with:  START_AT=6 $0"
printf '\n'
pause "Press Enter to start the transfer"
gate "archive transferred and checksum matches on the pod" \
  "${REPO_ROOT}/scripts/train/upload_bundle.sh" \
    --host "$CPU_POD_HOST" --port "$CPU_POD_PORT" --key "$SSH_KEY"
fi

# ── 7 ─────────────────────────────────────────────────────────────────────
stage "On the pod — extract the archive and clone the repo"
if _at; then
warn "Cloning into /workspace is not a style preference. Only /workspace is the"
warn "network volume; a repo anywhere else takes runs/ down with the pod."
say "Extracting 109,033 files onto network storage — metadata-heavy, so this can"
say "take several minutes. That is normal, not a hang."
podssh "$CPU_POD_HOST" "$CPU_POD_PORT" \
  "cd /workspace && tar -xf bundle.tar && echo extracted"
say "Cloning the repo..."
podssh "$CPU_POD_HOST" "$CPU_POD_PORT" \
  "cd /workspace && { [ -d second-vision-ai ] && git -C second-vision-ai pull --ff-only || git clone ${REPO_URL}; }"
note "bundle.tar is deliberately KEPT — 5.1 GB of a 30 GB volume, and the only copy"
note "on this side of a 2.2-hour uplink. Do not delete it to save space."
fi

# ── 8 ─────────────────────────────────────────────────────────────────────
stage "GATE — verify the bundle landed intact"
if _at; then
say "Recomputes the name+size digest through the same code path that wrote it, and"
say "resolves all three manifests. Nothing past this point runs until it passes."
if gate "bundle verified (digest + manifests)" \
     podssh "$CPU_POD_HOST" "$CPU_POD_PORT" \
     "python3 /workspace/second-vision-ai/scripts/train/verify_bundle.py --bundle /workspace/bundle"; then
  VERIFIED_OK=1
fi
fi

# ── 9 ─────────────────────────────────────────────────────────────────────
stage "Materialise cap${CAP} — on the cheap pod, not the 4090"
if _at; then
say "Hardlinks one image + one label per selected file. Pure metadata I/O, no GPU"
say "involved — doing it here means the 4090 starts with the dataset laid out."
gate "condition materialised" \
  podssh "$CPU_POD_HOST" "$CPU_POD_PORT" \
  "python3 /workspace/second-vision-ai/scripts/train/materialize_condition.py --bundle /workspace/bundle --cap ${CAP} --force"
gate "split counts are exactly ${EXP_TRAIN} / 6644 / 6403" \
  podssh "$CPU_POD_HOST" "$CPU_POD_PORT" \
  "python3 -c \"
import pathlib,sys
w='/workspace/${COND}'
g={s:len(list(pathlib.Path(f'{w}/{s}/images').iterdir())) for s in ('train','val','test')}
print(g)
sys.exit(0 if g=={'train':${EXP_TRAIN},'val':6644,'test':6403} else 1)\""
fi

# ── 10 ────────────────────────────────────────────────────────────────────
stage "TERMINATE the CPU pod — not Stop"
if _at; then
DO_TERMINATE=1
if [[ "$VERIFIED_OK" -ne 1 ]]; then
  warn "Stage 8 did not pass in this run, so terminating now could destroy the only"
  warn "pod attached to an unverified bundle."
  if ! confirm "Terminate anyway? (No is the right answer unless you verified earlier)"; then
    DO_TERMINATE=0
    say "Skipping termination — the pod stays up. Verify first:  START_AT=8 $0"
    pause "Press Enter to continue"
  fi
fi
if [[ "${DO_TERMINATE:-1}" -eq 1 ]]; then
warn "TERMINATE, do not Stop. A stopped pod keeps billing for its container disk."
say "Terminating destroys the container disk. These all survive on the volume:"
note "  /workspace/bundle.tar   /workspace/bundle   /workspace/${COND}"
note "  /workspace/second-vision-ai  (including runs/ later)"
say "Installed pip packages do not survive — expected; the CPU pod needed none."
open_url "https://console.runpod.io/pods"
step "Find the CPU pod → Terminate."
step "While you are here: terminate the STOPPED pod from the Hailo toolchain"
step "session too — it is still billing for 50 GB."
pause "Press Enter once terminated"
fi
fi

# ── 11 ────────────────────────────────────────────────────────────────────
stage "Deploy the RTX 4090 — same datacenter, same volume"
if _at; then
open_url "https://console.runpod.io/deploy"
step "Deploy an RTX 4090 pod in ${RUNPOD_DATACENTER} (A6000 is the fallback)."
step "Attach the EXISTING network volume — do not create a new one."
step "Use a PyTorch template (it ships a CUDA-matched torch)."
step "Expose TCP port 22, and HTTP port 6006 for live TensorBoard."
note "The volume mounts at /workspace again, so every path from here still resolves."
ask GPU_POD_HOST "Pod IP address:"
ask GPU_POD_PORT "Pod SSH port:"
write_env GPU_POD_HOST "$GPU_POD_HOST"
write_env GPU_POD_PORT "$GPU_POD_PORT"
gate "SSH to the GPU pod works" podssh "$GPU_POD_HOST" "$GPU_POD_PORT" true
gate "the volume came across (${COND} is present)" \
  podssh "$GPU_POD_HOST" "$GPU_POD_PORT" "test -d /workspace/${COND}"
fi

# ── 12 ────────────────────────────────────────────────────────────────────
stage "Install the pinned environment — and prove CUDA survived it"
if _at; then
say "requirements-train.txt deliberately does not name torch: the template ships a"
say "CUDA-matched build, and letting pip resolve torch usually swaps in a CPU-only"
say "wheel. Training then runs ~50x slower and reports no error at all."
podssh "$GPU_POD_HOST" "$GPU_POD_PORT" \
  "cd /workspace/second-vision-ai && git pull --ff-only && pip install -r requirements-train.txt"
gate "torch sees the GPU and ultralytics is 8.4.118" \
  podssh "$GPU_POD_HOST" "$GPU_POD_PORT" \
  "python3 -c \"
import torch,ultralytics,sys
print('torch',torch.__version__,'cuda',torch.cuda.is_available())
print('ultralytics',ultralytics.__version__)
sys.exit(0 if torch.cuda.is_available() and ultralytics.__version__=='8.4.118' else 1)\""

printf '\n'
if confirm "Set up Comet logging? (needs your Comet API key)"; then
  open_url "https://www.comet.com/account-settings/apiKeys"
  ask_secret COMET_API_KEY "Paste your Comet API key:"
  write_env COMET_API_KEY "$COMET_API_KEY"
  podssh "$GPU_POD_HOST" "$GPU_POD_PORT" \
    "grep -q COMET_API_KEY ~/.bashrc || echo 'export COMET_API_KEY=${COMET_API_KEY}' >> ~/.bashrc"
  note "Written to the pod's ~/.bashrc. train.py reports ARMED / NOT ARMED at start —"
  note "check it, because Comet fails soft and a silent no-op is only noticed at write-up."
else
  SKIPPED+=("Comet API key — TensorBoard still logs locally; train.py will report Comet NOT ARMED")
fi
fi

# ── 13 ────────────────────────────────────────────────────────────────────
stage "GATE — data.yaml resolves from an unrelated directory"
if _at; then
say "This is what DEC-066 exists for. A data.yaml that only resolves from its own"
say "directory works locally and fails on the pod."
gate "check_det_dataset() from /tmp returns nc=15 with canonical names" \
  podssh "$GPU_POD_HOST" "$GPU_POD_PORT" \
  "cd /tmp && python3 -c \"
from ultralytics.data.utils import check_det_dataset as c
import sys
d=c('/workspace/${COND}/data.yaml')
names=[d['names'][i] for i in sorted(d['names'])]
print(d['nc'], names)
sys.exit(0 if d['nc']==15 and names[0]=='Person' and names[13]=='Stairs' and names[14]=='Bench' else 1)\""
fi

# ── 14 ────────────────────────────────────────────────────────────────────
stage "GATE — smoke run, then hand off to the real thing"
if _at; then
say "2 epochs on 2% of the data, ~2 minutes. Exercises dataloader, AMP, both"
say "loggers, checkpoint writing and plots before you commit ~6 GPU-hours."
gate "smoke run completed" \
  podssh "$GPU_POD_HOST" "$GPU_POD_PORT" \
  "cd /workspace/second-vision-ai && python3 scripts/train/train.py --data /workspace/${COND}/data.yaml --device 0 --smoke"
printf '\n'
step "In that output, confirm: 'schema check: data.yaml agrees with classes.yaml at nc=15'"
step "and 'logger tensorboard: ARMED'."
note "Multiply its epoch time by ~50 for a full-epoch estimate (it trained on 2%),"
note "then by 100 epochs. Expect roughly 5-7 h."
pause "Press Enter when you have read the smoke output"

_clear
printf '\n%s%s  Ready for the baseline run%s\n\n' "$BOLD" "$GREEN" "$RESET"
say "SSH in and launch it DETACHED — an SSH drop otherwise kills training:"
printf '\n'
printf '    ssh -p %s -i %s root@%s\n' "$GPU_POD_PORT" "$SSH_KEY" "$GPU_POD_HOST"
printf '    tmux new -s train\n'
printf '    cd /workspace/second-vision-ai\n'
printf '    python3 scripts/train/train.py \\\n'
printf '      --data /workspace/${COND}/data.yaml \\\n'
printf '      --device 0 --batch 32 --name cap${CAP}_yolov8s\n'
printf '\n'
say "Live TensorBoard, in a second pod shell:"
printf '    tensorboard --logdir runs/detect --host 0.0.0.0 --port 6006\n'
printf '    then open  https://<pod-id>-6006.proxy.runpod.net\n'
printf '\n'
warn "Before deleting the volume, pull the results down to your laptop:"
printf '    rsync -avP -e "ssh -p %s -i %s" \\\n' "$GPU_POD_PORT" "$SSH_KEY"
printf '      root@%s:/workspace/second-vision-ai/runs/detect/cap${CAP}_yolov8s ./runs/detect/\n' "$GPU_POD_HOST"
printf '\n'
note "Full reference: docs/RUNPOD_TRAINING_RUNBOOK.md"
pause "Press Enter to finish"
fi

finish
